FROM amazonlinux:latest

RUN yum -y install gcc zlib zlib-devel openssl openssl-devel wget gzip tar
WORKDIR /tmp
RUN wget -P /tmp/ https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tgz \
    && tar -xzvf /tmp/Python-3.6.1.tgz \
    && cd /tmp/Python-3.6.1 && ./configure && make \
    && make install \
    && yum clean all \
    && rm -rf /var/cache/yum


RUN python3 -m pip install --upgrade pip

CMD [ "/bin/bash" ]
